name: i18n_builder
description: A builder to automatically update i18n translation files for Flutter projects
version: 1.1.0
homepage: https://github.com/israelins85/i18n_builder
repository: https://github.com/israelins85/i18n_builder

environment:
    sdk: '>=3.8.0 <4.0.0'

dependencies:
    build: ^4.0.4
    source_gen: ^4.2.0
    path: ^1.9.1

dev_dependencies:
    build_runner: ^2.7.0
    build_config: ^1.2.0
    test: ^1.24.0
    lints: ^6.1.0
